service: linn-api-iftt-v2

provider:
  name: aws
  stage: production
  region: eu-west-1
  logRetentionInDays: 7

package:
  artifact: package.zip

functions:
  iftt:
    handler: "Linn.Api.Ifttt::Linn.Api.Ifttt.LambdaEntryPoint::FunctionHandlerAsync"
    description: IFTTT Backend
    runtime: dotnetcore2.1
    timeout: 30
    memorySize: 256
    environment:
        discoveryEndpoint: https://www.linn.co.uk/auth
        apiRoot: https://api.linn.co.uk
        iftttServiceKey: ${env:IFTTT_SERVICE_KEY}
        testClientId: ${env:IFTTT_TEST_CLIENT_ID}
        testClientSecret: ${env:IFTTT_TEST_CLIENT_SECRET}
        testUsername: ${env:IFTTT_TEST_USERNAME}
        testPassword: ${env:IFTTT_TEST_PASSWORD}
    events:
      - http: ANY {proxy+}
